TechCareerActivityProject.UI/Controllers/StageController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using TechCareerActivityProject.DAL.Data;
using TechCareerActivityProject.DAL.Models;

namespace TechCareerActivityProject.UI.Controllers
{
    public class StageController : Controller
    {
        public IActionResult Index(string value)
        {
            if (!string.IsNullOrEmpty(value))
            {
                var filteredStage = StageRepository.FilterStage(value);

                return View("Index", new Home { StageList = filteredStage });
            }
            var model = new Home()
            {
                StageList = StageRepository.Stages
            };
            return View(model);
        }

        public IActionResult Details(int id)
        {
            return View(StageRepository.GetById(id));
        }
    }
}

TechCareerActivityProject.UI/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TechCareerActivityProject.DAL.Data;
using TechCareerActivityProject.DAL.Models;

namespace TechCareerActivityProject.UI.ViewComponents
{
    public class GenresViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            
            return View(GenreRepository.Genres);
        }
    }
}

TechCareerActivityProject.UI/Views/Stage/Details.cshtml
@model TechCareerActivityProject.DAL.Models.Stage
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="subintro">
    <div class="container">
        <div class="row">
            <div class="span8">
            </div>

        </div>
    </div>
</section>
<section id="maincontent">
    <div class="container">
        <div class="row">
            <div class="span12">
                <article>
                    <div class="heading">
                        <h4>@Model.StageName</h4>
                    </div>
                    <div class="clearfix">
                    </div>
                    <div class="row">
                        <div class="span8">
                            <!-- start flexslider -->
                            <div class="flexslider">
                                <ul class="slides">
                                    <li>
                                        <img src="~/lumia/assets/img/dummies/stage/@Model.StageImage" alt="" />
                                    </li>
                                    <li>
                                        <img src="~/lumia/assets/img/dummies/stage/@Model.StageImage" alt="" />
                                    </li>
                                    <li>
                                        <img src="~/lumia/assets/img/dummies/stage/@Model.StageImage" alt="" />
                                    </li>
                                </ul>
                            </div>
                            <!-- end flexslider -->
                            <p>
                                @Model.StageDescription
                                Cu cum noster euismod appellantur, mundi vitae vim ut, ea sea scripta expetendis vituperatoribus. Et cibo dicat impetus cum, id his quodsi scripserit. Nec purto habeo recteque eu. Posse oportere accusamus an sit, ex quando phaedrum sapientem ius. Perfecto
                                ocurreret no nam, eu quas cetero qui, vel ea minim nusquam salutatus. Nemore integre his ei, tollit eirmod eam at.
                            </p>
                        </div>
                        <div class="span4">
                            <aside>
                                <div class="widget">
                                    <div class="project-widget">
                                        <h4 class="rheading">Sahne detayı<span></span></h4>
                                        <ul class="project-detail">
                                            <li><label>Sahne adı :</label> @Model.StageName</li>

                                            <li><label>Sahne tarihi :</label> @Model.StageTime</li>
                                            <li><label>Sahne yeri :</label> @Model.StageLocation</li>
                                        </ul>
                                    </div>
                                </div>
                            </aside>
                        </div>
                    </div>
                </article>
                <!-- end article full post -->
            </div>
        </div>
    </div>
</section>

TechCareerActivityProject.UI/Views/Stage/Index.cshtml
@model TechCareerActivityProject.DAL.Models.Home
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header
{
    @await Html.PartialAsync("_header")
}


<section id="maincontent">
    <div class="container">
        <div class="row">
            <div class="span4">
                <h2>..</h2>
                <aside>
                    <div class="widget">
                        <h4 class="rheading">Öne Çıkanlar<span></span></h4>
                        @await Component.InvokeAsync("Genres")
                    </div>
                </aside>
            </div>

            <div class="span8">
                <h2>Sahne Listesi</h2>
                <div id="concerts">
                    @foreach (var item in Model.StageList)
                    {
                        <div class="concert">
                            <img src="~/lumia/assets/img/dummies/stage/@item.StageImage" alt="@item.StageType" width="200" height="250" />
                            <p>@item.StageName</p>
                            <p>@item.StageDescription</p>
                            <p>@item.StageTime</p>
                            <p>@item.StageLocation</p>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>